background {
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.26
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(56949fee)
    inner_color = rgba(1a1a1aee)
    font_color = rgb(f2e9e1)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 10
    position = 0, -20
    halign = center
    valign = center
}

label {
    text = $TIME
    color = rgb(f2e9e1)
    font_size = 64
    font_family = Sans
    position = 0, 80
    halign = center
    valign = center
}
